package pojos;
// Generated 19/01/2018 10:51:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private Electivo electivo;
     private Persona persona;
     private Representante representante;
     private String curso;
     private String paralelo;
     private float estaturaInicial;
     private float pesoInicial;
     private Float estaturaFinal;
     private Float pesoFinal;
     private Byte seEnvioFormulario;
     private Byte seRecibioFormulario;
     private String alergia;
     private Set historialclinicos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(Electivo electivo, Persona persona, Representante representante, String curso, String paralelo, float estaturaInicial, float pesoInicial) {
        this.electivo = electivo;
        this.persona = persona;
        this.representante = representante;
        this.curso = curso;
        this.paralelo = paralelo;
        this.estaturaInicial = estaturaInicial;
        this.pesoInicial = pesoInicial;
    }
    public Alumno(Electivo electivo, Persona persona, Representante representante, String curso, String paralelo, float estaturaInicial, float pesoInicial, Float estaturaFinal, Float pesoFinal, Byte seEnvioFormulario, Byte seRecibioFormulario, String alergia, Set historialclinicos) {
       this.electivo = electivo;
       this.persona = persona;
       this.representante = representante;
       this.curso = curso;
       this.paralelo = paralelo;
       this.estaturaInicial = estaturaInicial;
       this.pesoInicial = pesoInicial;
       this.estaturaFinal = estaturaFinal;
       this.pesoFinal = pesoFinal;
       this.seEnvioFormulario = seEnvioFormulario;
       this.seRecibioFormulario = seRecibioFormulario;
       this.alergia = alergia;
       this.historialclinicos = historialclinicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Electivo getElectivo() {
        return this.electivo;
    }
    
    public void setElectivo(Electivo electivo) {
        this.electivo = electivo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Representante getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(Representante representante) {
        this.representante = representante;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public float getEstaturaInicial() {
        return this.estaturaInicial;
    }
    
    public void setEstaturaInicial(float estaturaInicial) {
        this.estaturaInicial = estaturaInicial;
    }
    public float getPesoInicial() {
        return this.pesoInicial;
    }
    
    public void setPesoInicial(float pesoInicial) {
        this.pesoInicial = pesoInicial;
    }
    public Float getEstaturaFinal() {
        return this.estaturaFinal;
    }
    
    public void setEstaturaFinal(Float estaturaFinal) {
        this.estaturaFinal = estaturaFinal;
    }
    public Float getPesoFinal() {
        return this.pesoFinal;
    }
    
    public void setPesoFinal(Float pesoFinal) {
        this.pesoFinal = pesoFinal;
    }
    public Byte getSeEnvioFormulario() {
        return this.seEnvioFormulario;
    }
    
    public void setSeEnvioFormulario(Byte seEnvioFormulario) {
        this.seEnvioFormulario = seEnvioFormulario;
    }
    public Byte getSeRecibioFormulario() {
        return this.seRecibioFormulario;
    }
    
    public void setSeRecibioFormulario(Byte seRecibioFormulario) {
        this.seRecibioFormulario = seRecibioFormulario;
    }
    public String getAlergia() {
        return this.alergia;
    }
    
    public void setAlergia(String alergia) {
        this.alergia = alergia;
    }
    public Set getHistorialclinicos() {
        return this.historialclinicos;
    }
    
    public void setHistorialclinicos(Set historialclinicos) {
        this.historialclinicos = historialclinicos;
    }




}


