package pojos;
// Generated 19/01/2018 10:51:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Electivo generated by hbm2java
 */
public class Electivo  implements java.io.Serializable {


     private Integer id;
     private String desde;
     private String hasta;
     private Set alumnos = new HashSet(0);

    public Electivo() {
    }

	
    public Electivo(String desde, String hasta) {
        this.desde = desde;
        this.hasta = hasta;
    }
    public Electivo(String desde, String hasta, Set alumnos) {
       this.desde = desde;
       this.hasta = hasta;
       this.alumnos = alumnos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesde() {
        return this.desde;
    }
    
    public void setDesde(String desde) {
        this.desde = desde;
    }
    public String getHasta() {
        return this.hasta;
    }
    
    public void setHasta(String hasta) {
        this.hasta = hasta;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    
    @Override
    public String toString(){
        return this.desde+"-"+this.hasta;
    }



}


