package pojos;
// Generated 07/02/2018 12:49:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Representante generated by hbm2java
 */
public class Representante  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private String contacto;
     private Set alumnos = new HashSet(0);

    public Representante() {
    }

	
    public Representante(String nombres, String apellidos, String contacto) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.contacto = contacto;
    }
    public Representante(String nombres, String apellidos, String contacto, Set alumnos) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.contacto = contacto;
       this.alumnos = alumnos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    @Override
    public String toString(){
        return this.nombres+" "+this.apellidos;
    }




}


