/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pojos.Persona;
import recursos.Soporte.Herramientas;
import static recursos.Soporte.Herramientas.toByte;
import recursos.conexion.hPersona;

/**
 *
 * @author PC
 */
public class jiActualizarVacunas extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    Persona persona;

    public jiActualizarVacunas() {
        initComponents();
        cargarPersonas();
        jchHpv01.setEnabled(false);
        jchHpv02.setEnabled(false);
        jchSrp01.setEnabled(false);
        jchSrp02.setEnabled(false);
        jchInfluencia.setEnabled(false);
    }

    private void cargarPersonas() {
        List<Persona> personas = hPersona.obtenerPersonas();
        Iterator it = personas.iterator();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        Persona aux = new Persona();
        aux.setNombres("");
        aux.setApellidos("");
        modelo.addElement(aux);
        for (Iterator<Persona> iterator = personas.iterator(); iterator.hasNext();) {
            Persona next = iterator.next();
            modelo.addElement(next);
        }
        jcbAlumnos.setModel(modelo);
        AutoCompleteDecorator.decorate(jcbAlumnos);
    }

    private void cargarVacunas() {
        jchHpv01.setSelected(persona.getHpv01() == 1);
        jchHpv02.setSelected(persona.getHpv02() == 1);
        jchSrp01.setSelected(persona.getSrp01() == 1);
        jchSrp02.setSelected(persona.getSrp02() == 1);
        jchInfluencia.setSelected(persona.getInfluencia() == 1);
    }

    public void actualizarVacunas() {
        persona.setHpv01(toByte(jchHpv01.isSelected()));
        persona.setHpv02(toByte(jchHpv02.isSelected()));
        persona.setSrp01(toByte(jchSrp01.isSelected()));
        persona.setSrp02(toByte(jchSrp02.isSelected()));
        persona.setInfluencia(toByte(jchInfluencia.isSelected()));
        if (hPersona.editarPersona(persona)) {
            Herramientas.MensajeInfo("Vacunas actualizadas");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        jpnVacunas = new javax.swing.JPanel();
        jchSrp01 = new javax.swing.JCheckBox();
        jchSrp02 = new javax.swing.JCheckBox();
        jchHpv01 = new javax.swing.JCheckBox();
        jchHpv02 = new javax.swing.JCheckBox();
        jchInfluencia = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Actualización vacunas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Alumno");

        jcbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnosActionPerformed(evt);
            }
        });

        jpnVacunas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacunas"));

        jchSrp01.setText("SRP01");
        jchSrp01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchSrp01ActionPerformed(evt);
            }
        });

        jchSrp02.setText("SRP02");

        jchHpv01.setText("HPV01");
        jchHpv01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchHpv01ActionPerformed(evt);
            }
        });

        jchHpv02.setText("HPV02");

        jchInfluencia.setText("Influenza");

        javax.swing.GroupLayout jpnVacunasLayout = new javax.swing.GroupLayout(jpnVacunas);
        jpnVacunas.setLayout(jpnVacunasLayout);
        jpnVacunasLayout.setHorizontalGroup(
            jpnVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnVacunasLayout.createSequentialGroup()
                        .addComponent(jchSrp01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchSrp02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchHpv01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchHpv02))
                    .addComponent(jchInfluencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnVacunasLayout.setVerticalGroup(
            jpnVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchSrp01)
                    .addComponent(jchSrp02)
                    .addComponent(jchHpv01)
                    .addComponent(jchHpv02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchInfluencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnVacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jcbAlumnos.getSelectedIndex() > 0) {
            actualizarVacunas();
        } else {
            Herramientas.MensajeAdv("Debe seleccionar una persona");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnosActionPerformed
        if (jcbAlumnos.getSelectedIndex() > 0) {
            persona = (Persona) jcbAlumnos.getSelectedItem();
            jchHpv01.setSelected(true);
            jchHpv02.setSelected(true);
            jchSrp01.setSelected(true);
            jchSrp02.setSelected(true);
            jchInfluencia.setSelected(true);
            jchHpv01.setEnabled(true);
            jchHpv02.setEnabled(true);
            jchSrp01.setEnabled(true);
            jchSrp02.setEnabled(true);
            jchInfluencia.setEnabled(true);
            cargarVacunas();
        } else {
            jchHpv01.setSelected(false);
            jchHpv02.setSelected(false);
            jchSrp01.setSelected(false);
            jchSrp02.setSelected(false);
            jchInfluencia.setSelected(false);
            jchHpv01.setEnabled(false);
            jchHpv02.setEnabled(false);
            jchSrp01.setEnabled(false);
            jchSrp02.setEnabled(false);
            jchInfluencia.setEnabled(false);
        }
    }//GEN-LAST:event_jcbAlumnosActionPerformed

    private void jchSrp01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchSrp01ActionPerformed
        if (!jchSrp01.isSelected()) {
            jchSrp02.setSelected(false);
        }
        jchSrp02.setEnabled(jchSrp01.isSelected());
    }//GEN-LAST:event_jchSrp01ActionPerformed

    private void jchHpv01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchHpv01ActionPerformed
        if (!jchHpv01.isSelected()) {
            jchHpv02.setSelected(false);
        }
        jchHpv02.setEnabled(jchHpv01.isSelected());
    }//GEN-LAST:event_jchHpv01ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbAlumnos;
    private javax.swing.JCheckBox jchHpv01;
    private javax.swing.JCheckBox jchHpv02;
    private javax.swing.JCheckBox jchInfluencia;
    private javax.swing.JCheckBox jchSrp01;
    private javax.swing.JCheckBox jchSrp02;
    private javax.swing.JPanel jpnVacunas;
    // End of variables declaration//GEN-END:variables
}
