/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import recursos.Soporte.Herramientas;
import recursos.Soporte.conector;
import recursos.Soporte.consultas;

/**
 *
 * @author PC
 */
public class jiHistorialClinico extends javax.swing.JInternalFrame {

    /**
     * Creates new form jiHistorialClinico
     */
    public jiHistorialClinico() {
        initComponents();
        cargarAñosElectivos();
        String aux = new SimpleDateFormat("yyyy").format(Calendar.getInstance().getTime());
        for(int i = 0 ; i < jcbElectivo.getItemCount();i++){
            if(jcbElectivo.getItemAt(i).contentEquals(aux+"-")){
               jcbElectivo.setSelectedIndex(i);
                break;
            }
        }
    }
    int idAux;
    private void cargarAñosElectivos(){
        jcbElectivo.removeAllItems();
        ResultSet rs = consultas.obtenerAniosElectivos();
        if(rs!=null){
            try {
                while(rs.next()){
                    jcbElectivo.addItem(rs.getString(1)+"-"+rs.getString(2));
                }
                conector.cerrar(rs);
            } catch (SQLException ex) {
                Logger.getLogger(jiHistorialClinico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void cargarListaAlumno(){
        jcbAlumno.removeAllItems();
        jcbAlumno.addItem("");
        int idElectivo = consultas.obtenerIdElectivo(jcbElectivo.getSelectedItem().toString());
        ResultSet rs = consultas.listaEstudiantesPoridElectivo(idElectivo);
        if(rs!=null){
            try {
                while(rs.next()){
                    jcbAlumno.addItem(rs.getString(1)+" "+rs.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(jiHistorialClinico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void cargarListaHistoria(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Fecha");
        dtm.addColumn("Hora");
        dtm.addColumn("Enfermedad");
        int idEle = consultas.obtenerIdElectivo(jcbElectivo.getSelectedItem().toString());
        int idAl = consultas.obtenerIdAlumnoPorNombresApellidosIDElectivo(jcbAlumno.getSelectedItem().toString(),idEle);
        idAux = idAl;
        ResultSet rs = consultas.historialClinicoAlumno(idAl);
        if(rs!=null){
            try {
                while(rs.next()){
                    dtm.addRow(new String[]{new SimpleDateFormat("dd-MMM-yyyy").format(rs.getDate(1)),new SimpleDateFormat("hh:mm").format(rs.getTime(2)),rs.getString(3)}); 
                }
                conector.cerrar(rs);
            } catch (SQLException ex) {
                Logger.getLogger(jiHistorialClinico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jtHistorial.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbElectivo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHistorial = new javax.swing.JTable();
        jbNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtRepresentante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtContactoRepresentante = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jchSRP01 = new javax.swing.JCheckBox();
        jchSRP02 = new javax.swing.JCheckBox();
        jchHPV01 = new javax.swing.JCheckBox();
        jchHPV02 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jopEnviado = new javax.swing.JRadioButton();
        jopRecibido = new javax.swing.JRadioButton();
        jtxtDetalle = new javax.swing.JTextField();
        jcbFiltroHistorial = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Historial clinico");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Año electivo");

        jcbElectivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbElectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbElectivoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Alumno");

        jcbAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        jtHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtHistorial);

        jbNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setEnabled(false);
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Representante");

        jtxtRepresentante.setEditable(false);
        jtxtRepresentante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contacto");

        jtxtContactoRepresentante.setEditable(false);
        jtxtContactoRepresentante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtContactoRepresentante.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vacunas"));

        jchSRP01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jchSRP01.setText("S.R.P. 01");
        jchSRP01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchSRP01ActionPerformed(evt);
            }
        });

        jchSRP02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jchSRP02.setText("S.R.P. 02");
        jchSRP02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchSRP02ActionPerformed(evt);
            }
        });

        jchHPV01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jchHPV01.setText("H.P.V. 01");
        jchHPV01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchHPV01ActionPerformed(evt);
            }
        });

        jchHPV02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jchHPV02.setText("H.P.V. 02");
        jchHPV02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchHPV02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchSRP01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchSRP02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchHPV01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchHPV02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchSRP01)
                    .addComponent(jchSRP02)
                    .addComponent(jchHPV01)
                    .addComponent(jchHPV02))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario"));

        jopEnviado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jopEnviado.setText("Enviado");
        jopEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopEnviadoActionPerformed(evt);
            }
        });

        jopRecibido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jopRecibido.setText("Recibido");
        jopRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopRecibidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jopEnviado)
                .addGap(37, 37, 37)
                .addComponent(jopRecibido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jopEnviado)
                    .addComponent(jopRecibido))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtxtDetalle.setEditable(false);
        jtxtDetalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDetalle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtContactoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtContactoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcbFiltroHistorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbFiltroHistorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Esta semana", "Este mes", "Este año" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbElectivo, 0, 262, Short.MAX_VALUE)
                            .addComponent(jcbAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbFiltroHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(433, 433, 433)
                        .addComponent(jbNuevo))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbElectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jcbFiltroHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbElectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbElectivoActionPerformed
        cargarListaAlumno();
    }//GEN-LAST:event_jcbElectivoActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        if(jcbAlumno.getSelectedIndex()>0){
        cargarListaHistoria();
        
    }
       jbNuevo.setEnabled(jcbAlumno.getSelectedIndex()>0);
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        new jdNuevoHistorialClinico(null, true,jcbAlumno.getSelectedItem().toString(),idAux).show();
        cargarListaHistoria();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jchSRP01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchSRP01ActionPerformed
      jchSRP01.setSelected(!jchSRP01.isSelected());
    }//GEN-LAST:event_jchSRP01ActionPerformed

    private void jchSRP02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchSRP02ActionPerformed
         jchSRP02.setSelected(!jchSRP02.isSelected());
    }//GEN-LAST:event_jchSRP02ActionPerformed

    private void jchHPV01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchHPV01ActionPerformed
         jchHPV01.setSelected(!jchHPV01.isSelected());
    }//GEN-LAST:event_jchHPV01ActionPerformed

    private void jchHPV02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchHPV02ActionPerformed
        jchHPV02.setSelected(!jchHPV02.isSelected());
    }//GEN-LAST:event_jchHPV02ActionPerformed

    private void jopEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopEnviadoActionPerformed
        jopEnviado.setSelected(!jopEnviado.isSelected());
    }//GEN-LAST:event_jopEnviadoActionPerformed

    private void jopRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopRecibidoActionPerformed
        jopRecibido.setSelected(!jopRecibido.isSelected());
    }//GEN-LAST:event_jopRecibidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JComboBox<String> jcbAlumno;
    private javax.swing.JComboBox<String> jcbElectivo;
    private javax.swing.JComboBox<String> jcbFiltroHistorial;
    private javax.swing.JCheckBox jchHPV01;
    private javax.swing.JCheckBox jchHPV02;
    private javax.swing.JCheckBox jchSRP01;
    private javax.swing.JCheckBox jchSRP02;
    private javax.swing.JRadioButton jopEnviado;
    private javax.swing.JRadioButton jopRecibido;
    private javax.swing.JTable jtHistorial;
    private javax.swing.JTextField jtxtContactoRepresentante;
    private javax.swing.JTextField jtxtDetalle;
    private javax.swing.JTextField jtxtRepresentante;
    // End of variables declaration//GEN-END:variables
}
