/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import pojos.Persona;
import recursos.Soporte.Herramientas;
import recursos.Soporte.conector;
import recursos.Soporte.consultas;
import recursos.conexion.hPersona;

/**
 *
 * @author PC
 */
public class jpnAgregarAlumno extends javax.swing.JPanel {

    private Persona persona;

    public jpnAgregarAlumno() {
        initComponents();
    }

    public void calcularEdad() {
        jlbAnios.setText("" + Herramientas.CalcularEdad(jcalFecha.getSelectedDate().getTime()));
    }

    public void cargarDatosEdicion(Persona _persona) {
        persona = _persona;
        if (persona != null) {
            jtxtNombres.setText(persona.getNombres());
            jtxtApellidos.setText(persona.getApellidos());
            jopMas.setSelected(persona.getGenero().equals("M"));
            jopFem.setSelected(persona.getGenero().equals("F"));
            Calendar cal = Calendar.getInstance();
            cal.setTime(persona.getFechaNacimiento());
            jcalFecha.setSelectedDate(cal);
            jchHPV01.setSelected(persona.getHpv01() == 1);
            jchHPV02.setSelected(persona.getHpv02() == 1);
            jchSRP01.setSelected(persona.getSrp01() == 1);
            jchSRP02.setSelected(persona.getSrp02() == 1);
            jchHPV02.setEnabled(jchHPV01.isSelected());
            jchSRP02.setEnabled(jchSRP01.isSelected());
            jchInfluencia.setSelected(persona.getInfluencia() == 1);
            calcularEdad();
        }
    }

    public void setPersona(Persona _persona) {
        persona = _persona;
    }

    private boolean CamposLlenos() {
        return !jtxtNombres.getText().trim().isEmpty() && !jtxtApellidos.getText().trim().isEmpty() && (jopFem.isSelected() || jopMas.isSelected());
    }
    public boolean oyenteElectivo;
    public int lastID = -1;

    public boolean actualizarDatosPersonales() {
        Persona aux = hPersona.obtenerPersonaNombreApellidos(jtxtNombres.getText() + " " + jtxtApellidos.getText());
        if (aux != null) {
            if (aux.getId() != persona.getId()) {
                Herramientas.MensajeAdv("Ya existe un estudiante con los nombres " + jtxtNombres.getText() + " " + jtxtApellidos.getText() + " registrado.");
                return false;
            }
        }
        if (CamposLlenos()) {
            return hPersona.editarPersona(persona.getId(), jtxtNombres.getText(), jtxtApellidos.getText(), jopMas.isSelected() ? "M" : "F", jcalFecha.getSelectedDate().getTime(), jchSRP01.isSelected(), jchSRP02.isSelected(), jchHPV01.isSelected(), jchHPV02.isSelected(), jchInfluencia.isSelected());
        } else {
            Herramientas.MensajeAdv("Los datos personales y la fecha son campos obligatorios");
            return false;
        }
    }

    public boolean guardarDatosPersonales() {
        if (hPersona.obtenerPersonaNombreApellidos(jtxtNombres.getText() + " " + jtxtApellidos.getText()) != null) {
            Herramientas.MensajeAdv("Ya existe un estudiante con los nombres " + jtxtNombres.getText() + " " + jtxtApellidos.getText() + " registrado.");
            return false;
        }
        if (CamposLlenos()) {
            return hPersona.nuevaPersona(jtxtNombres.getText(), jtxtApellidos.getText(), jopMas.isSelected() ? "M" : "F", jcalFecha.getSelectedDate().getTime(), jchSRP01.isSelected(), jchSRP02.isSelected(), jchHPV01.isSelected(), jchHPV02.isSelected(), jchInfluencia.isSelected());
        } else {
            Herramientas.MensajeAdv("Los datos personales y la fecha son campos obligatorios");
            return false;
        }
    }

    public void cancelar() {
        jchInfluencia.setSelected(false);
        jtxtNombres.setText("");
        jtxtApellidos.setText("");
        jopFem.setSelected(false);
        jopMas.setSelected(false);
        jcalFecha.setText("");
        jchHPV01.setSelected(false);
        jchHPV02.setSelected(false);
        jchSRP01.setSelected(false);
        jchSRP02.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtxtNombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtApellidos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jopMas = new javax.swing.JRadioButton();
        jopFem = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jlbAnios = new javax.swing.JLabel();
        jcalFecha = new datechooser.beans.DateChooserCombo();
        jPanel4 = new javax.swing.JPanel();
        jchSRP01 = new javax.swing.JCheckBox();
        jchSRP02 = new javax.swing.JCheckBox();
        jchHPV01 = new javax.swing.JCheckBox();
        jchHPV02 = new javax.swing.JCheckBox();
        jchInfluencia = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N

        jtxtNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombresFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Nombres del estudiante");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Apellidos del estudiante");

        jtxtApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtApellidosFocusLost(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));

        grupoGenero.add(jopMas);
        jopMas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jopMas.setText("Masculino");

        grupoGenero.add(jopFem);
        jopFem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jopFem.setText("Femenino");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jopMas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jopFem)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jopMas)
                    .addComponent(jopFem))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Fecha nacimiento");

        jlbAnios.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAnios.setText("00");

        jcalFecha.setCalendarPreferredSize(new java.awt.Dimension(350, 300));
        jcalFecha.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                jcalFechaOnCommit(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcalFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtApellidos)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtNombres)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbAnios)
                    .addComponent(jcalFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vacunas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N

        jchSRP01.setText("SRP 01");
        jchSRP01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchSRP01ActionPerformed(evt);
            }
        });

        jchSRP02.setText("SRP 02");
        jchSRP02.setEnabled(false);

        jchHPV01.setText("HPV 01");
        jchHPV01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchHPV01ActionPerformed(evt);
            }
        });

        jchHPV02.setText("HPV 02");
        jchHPV02.setEnabled(false);

        jchInfluencia.setText("Influencia");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jchSRP01)
                        .addGap(18, 18, 18)
                        .addComponent(jchSRP02))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jchHPV01)
                        .addGap(18, 18, 18)
                        .addComponent(jchHPV02))
                    .addComponent(jchInfluencia))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchSRP01)
                    .addComponent(jchSRP02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchHPV01)
                    .addComponent(jchHPV02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchInfluencia)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombresFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresFocusLost

    private void jtxtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtApellidosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidosFocusLost

    private void jchSRP01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchSRP01ActionPerformed
        jchSRP02.setEnabled(jchSRP01.isSelected());
        jchSRP02.setSelected(false);
    }//GEN-LAST:event_jchSRP01ActionPerformed

    private void jchHPV01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchHPV01ActionPerformed
        jchHPV02.setEnabled(jchHPV01.isSelected());
        jchHPV02.setSelected(false);
    }//GEN-LAST:event_jchHPV01ActionPerformed

    private void jcalFechaOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_jcalFechaOnSelectionChange
        calcularEdad();
    }//GEN-LAST:event_jcalFechaOnSelectionChange

    private void jcalFechaOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_jcalFechaOnCommit
        calcularEdad();
    }//GEN-LAST:event_jcalFechaOnCommit


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private datechooser.beans.DateChooserCombo jcalFecha;
    private javax.swing.JCheckBox jchHPV01;
    private javax.swing.JCheckBox jchHPV02;
    private javax.swing.JCheckBox jchInfluencia;
    private javax.swing.JCheckBox jchSRP01;
    private javax.swing.JCheckBox jchSRP02;
    private javax.swing.JLabel jlbAnios;
    private javax.swing.JRadioButton jopFem;
    private javax.swing.JRadioButton jopMas;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
