package ventanas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pojos.Representante;
import recursos.Soporte.Herramientas;
import recursos.Soporte.consultas;
import recursos.conexion.hRepresentante;

/**
 *
 * @author PC
 */
public class jpnRepresentante extends javax.swing.JPanel {

    /**
     * Creates new form jpnRepresentante
     */
    public boolean guardado;
    private Representante representante;
    public jpnRepresentante() {
        initComponents();
    }
    public boolean guardarRepresentante(){
    if(!jtxtNombres.getText().trim().isEmpty() &&  !jtxtApellidos.getText().trim().isEmpty() && !jtxtContacto.getText().trim().isEmpty()){
        if(hRepresentante.obtenerRepresentante(jtxtNombres.getText()+" "+jtxtApellidos.getText())!=null){
            Herramientas.MensajeAdv("Ya existe un representante con el nombre "+jtxtNombres.getText()+" "+jtxtApellidos.getText()+" registrado.");
            return false;
        }
        if(hRepresentante.nuevoRepresentante(jtxtNombres.getText(), jtxtApellidos.getText(),jtxtContacto.getText())){
          return true; 
        }
    }
    return false;
}
    public void cargarRepresentante(Representante _representante){
        soloEditarContacto();
        representante = _representante;
        jtxtNombres.setText(_representante.getNombres());
        jtxtApellidos.setText(_representante.getApellidos());
        jtxtContacto.setText(_representante.getContacto());
    }
    public void soloEditarContacto(){
        jtxtApellidos.setEditable(false);
        jtxtNombres.setEditable(false);
    }
    
public boolean editarRepresentante(){
    if(!jtxtContacto.getText().trim().isEmpty()){
        if(hRepresentante.editarRepresentante(representante.getId(), jtxtNombres.getText(), jtxtApellidos.getText(),jtxtContacto.getText()))
        {
             return true;
        }
    }
    return false;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtContacto = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Nombres del representante");

        jtxtNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtNombres.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Apellidos del representante");

        jtxtApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtApellidos.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Contacto");

        jtxtContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtContacto.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jtxtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtContacto;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
